on:
  push:
    branches:
      - main

jobs:
  linux-build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-add-repository ppa:hrzhu/sdl2-backport
        sudo apt-get update
        sudo apt-get install ninja-build libsdl2-dev
    - uses: goto-bus-stop/setup-zig@v2

    - run: cd Native && zig build --release=fast

    - name: Upload Artifact (Linux)
      uses: actions/upload-artifact@v1
      with:
        name: linux
        path: ./Native/zig-out/lib
        retention-days: 2
      if: matrix.os == 'ubuntu-latest'

  windows-build:
    name: Windows (MinGW)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw32
        install: >-
          mingw-w64-i686-cc
          mingw-w64-i686-cmake
          mingw-w64-i686-ninja
          mingw-w64-i686-pkg-config
          mingw-w64-i686-SDL2

    - uses: goto-bus-stop/setup-zig@v2

    - run: cd Native && zig build --release=fast

    - name: Upload Artifact (Windows)
      uses: actions/upload-artifact@v1
      with:
        name: windows
        path: ./Native/zig-out/lib
        retention-days: 2
  macos-build:
    name: MacOS
    runs-on: macos-latest
    steps:
      env:
        CXXFLAGS: -I/usr/local/include/SDL2
        LDFLAGS: -L/usr/local/lib
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2

      - run: cd Native && zig build --release=fast

      - name: Upload Artifact (Mac OS)
        uses: actions/upload-artifact@v1
        with:
          name: macOS
          path: ./Native/zig-out/lib
          retention-days: 2
